I_shop/ecommerce/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('products.urls', namespace='mainapp')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

I_shop/products/urls.py
from django.urls import path
from . views import Home, ProductDetailView
from cart.views import add_to_cart, remove_from_cart, CartView, decreaseCart
app_name= 'mainapp'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path(r'^product/(?P<pk>\d+)$', ProductDetailView.as_view(), name='product-detail'),
    path('find/<category>', Home.as_view(), name='home'),
    path('cart/', CartView, name='cart-home'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('decrease-cart/<slug>', decreaseCart, name='decrease-cart'),
    path('remove/<slug>', remove_from_cart, name='remove-cart'),
    path('find/cart/', CartView, name='cart-home'),
    path('find/cart/<slug>', add_to_cart, name='cart'),
    path('find/decrease-cart/<slug>', decreaseCart, name='decrease-cart'),
    path('find/remove/<slug>', remove_from_cart, name='remove-cart'),
]

I_shop/cart/models.py
from django.contrib.auth import get_user_model
from products.models import Product
from django.db import models


# Get the user model
User = get_user_model()


# Cart Model
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.quantity} of {self.item.name}'
    
    def get_total(self):
        return self.item.price * self.quantity

class Order(models.Model):
    orderitems  = models.ManyToManyField(Cart)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    
    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total += order_item.get_total()
        
        return total

I_shop/products/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    class Meta: 
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    title = models.CharField(max_length=300)
    

    def __str__(self):
        """
        Переопределение перевода объекта в строку. Возвращает имя объекта
        """
        return self.title

#Product Model
class  Product(models.Model):


    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    mainimage = models.ImageField(upload_to='products/', blank=True)
    name = models.CharField(max_length=300, verbose_name='Название')
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    preview_text = models.TextField(max_length=200, verbose_name='Текст превью')
    detail_text = models.TextField(max_length=1000, verbose_name='Подробный текст')
    price = models.FloatField(verbose_name='Цена')
    

    def get_absolute_url(self):
         """
         Возвращает путь к конкретному объекту
         """
         return reverse('mainapp:product-detail', args=[str(self.id)])

    def __str__(self):
        """
        Переопределение перевода объекта в строку. Возвращает имя объекта
        """
        return self.name

    

I_shop/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Order, Cart
from products.models import Product
from django.contrib import messages
# Create your views here.

def add_to_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    if request.user.is_anonymous:
        messages.warning(request, "Вы не зарегистрированны!")
        return redirect("/accounts/login/")
    order_item, created = Cart.objects.get_or_create(
        item=item,
        user=request.user
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # проверить, есть ли товар в заказе
        if order.orderitems.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "Число товара измененно")
            return redirect("mainapp:cart-home")
        else:
            order.orderitems.add(order_item)
            messages.info(request, "Товар добавлен в корзину.")
            return redirect("mainapp:home")
    else:
        order = Order.objects.create(
            user=request.user)
        order.orderitems.add(order_item)
        messages.info(request, "Товар добавлен в корзину.")
        return redirect("mainapp:home")
    

def remove_from_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    if request.user.is_anonymous:
        messages.warning(request, "Вы не зарегистрированны!")
        return redirect("/accounts/login/")
    cart_qs = Cart.objects.filter(user=request.user, item=item)
    if cart_qs.exists():
        cart = cart_qs[0]
        # Проверка численности корзины
        if cart.quantity > 1:
            cart.quantity -= 1
            cart.save()
        else:
            cart_qs.delete()
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # проверить, есть ли товар в заказе
        if order.orderitems.filter(item__slug=item.slug).exists():
            order_item = Cart.objects.filter(
                item=item,
                user=request.user,
            )[0]
            order.orderitems.remove(order_item)
            messages.info(request, "Товар убран из корзины.")
            return redirect("mainapp:home")
        else:
            messages.info(request, "Этого товара и так не было в корзине!")
            return redirect("mainapp:home")
    else:
        messages.info(request, "У вас не активного заказа")
        return redirect("core:home")


def CartView(request):

    user = request.user
    if user.is_anonymous:
        messages.warning(request, "Вы не зарегистрированны!")
        return redirect("/accounts/login/")
    else:
        carts = Cart.objects.filter(user=user)
        orders = Order.objects.filter(user=user, ordered=False)

        if carts.exists():
            order = orders[0]
            return render(request, 'cart/home.html', {"carts": carts, 'order': order})
            
        else:
            messages.warning(request, "У Вас нет активных заказов")
            return redirect("mainapp:home")


def decreaseCart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # проверить, есть ли товар в заказе
        if order.orderitems.filter(item__slug=item.slug).exists():
            order_item = Cart.objects.filter(
                item=item,
                user=request.user
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.orderitems.remove(order_item)
                order_item.delete()
            messages.info(request, f"Количество {item.name} обновленно.")
            return redirect("mainapp:cart-home")
        else:
            messages.info(request, f"Количество {item.name} обновленно.")
            return redirect("mainapp:cart-home")
    else:
        messages.info(request, "У вас нет активного заказа")
        return redirect("mainapp:cart-home")

I_shop/products/views.py
from unicodedata import category, name
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView
from products.models import Product, Category

class Home(ListView):
    model = Product
    template_name = 'products/home.html'

    def get_queryset(self): #получаем список продуктов
        filter_name = self.request.path
        print(filter_name)
        if filter_name != "/":
            try:
                filter_name=filter_name.replace('/find/','') #если идёт поиск по категории 
                cat = Category.objects.filter(title=filter_name)[0] #получаем категорию по названию
                return Product.objects.filter(category=cat) #фильтруем по ней
            except:
                return Product.objects.all()
        else:
            return Product.objects.all()

class ProductDetailView(DetailView):
    model = Product

I_shop/cart/templates/cart/home.html
{% extends 'products/base.html' %}

{% block content %}
<div class="container my-5">
<div class="my-5">
	<h2>Ваша корзина</h2>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Название</th>
      <th scope="col">Количество</th>
      <th scope="col">Цена</th>
    </tr>
  </thead>
  <tbody>
  	{% for cart in carts %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ cart.item.name }}</td>
      <td>
        <a class="mr-2" href="{% url 'mainapp:decrease-cart' cart.item.slug %}"><span class="badge badge-light"><i class="fas fa-minus"></i></span></a>
      {{ cart.quantity }}
      <a class="ml-2" href="{% url 'mainapp:cart' cart.item.slug %}" ><span class="badge badge-light"><i class="fas fa-plus"></i></span></a>
      </td>
      <td>{{ cart.get_total }} руб</td>
    </tr>
	{% endfor %}
    <tr>
      <th scope="row"></th> 
      <td colspan="2">Итого:</td>
      <td>{{ order.get_totals| floatformat:2 }} руб</td>
    </tr>
    <tr>
      <th scope="row"></th>
      <td colspan="3" class="text-right ">
        <a href="{% url 'mainapp:home' %}" class="btn btn-warning mr-4" >Вернуться</a>
      </td>
    </tr>
  </tbody>
</table>
</div>

{% endblock %}

I_shop/products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <title>Бомжатник</title>
  <style>
  	.card{
  		    height: 350px;
  	}
  	.card-product:after {
    content: "";
    display: table;
    clear: both;
    visibility: hidden; }
  .card-product .price-new, .card-product .price {
    margin-right: 5px; }
  .card-product .price-old {
    color: #999; }
  .card-product .img-wrap {
    border-radius: 3px 3px 0 0;
    overflow: hidden;
    position: relative;
    height: 220px;
    text-align: center; }
    .card-product .img-wrap img {
      max-height: 100%;
      max-width: 100%;
      object-fit: cover; }
      
      .card-product .info-wrap {
    overflow: hidden;
    padding: 15px;
    border-top: 1px solid #eee; }
  .card-product .action-wrap {
    padding-top: 4px;
    margin-top: 4px; }
  .card-product .bottom-wrap {
    padding: 15px;
    border-top: 1px solid #eee; }
  .card-product .title {
    margin-top: 0; }
  </style>
</head>
<body>
{% include 'products/navbar.html' %}


    {% if messages %}
    <div class="messages container mt-2">
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
        </div>
        {% endfor %}
    </div>
  {% endif %}
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script>
  
</script>
</body>
</html>

I_shop/products/templates/products/home.html
{% extends 'products/base.html' %}

{% block content %}

  <div class="container my-5">
  	
    <div class="row">
    <div class="col-md-9">
		<div class="row">
			{% if object_list %}
			{% for product in object_list  %}
		  <div class="col-md-6 col-sm-12 col-lg-4">
			<figure class="card card-product">
				<div class="img-wrap"> 
					<img src="{{ product.mainimage.url }}" style="width: 100%; height: 300px;">
				</div>
				<figcaption class="info-wrap">
					<h6 class="title text-dots"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h6>
					
					<div class="action-wrap">
						<h6 class="title text-dots">{{ product.preview_text }}</h6>
						<a href="cart/{{ product.slug }}" class="btn btn-primary btn-sm"> Добавить в корзину </a>
             			<a href="remove/{{ product.slug }}" class="btn btn-danger btn-sm"> Убрать из корзины</a>
 						<!-- price-wrap.// -->
						 <div class="price-wrap h5">
							<span class="price-new">{{product.price}} руб</span>
						</div> 
					</div> <!-- action-wrap -->
				</figcaption>
			</figure> <!-- card // -->
		</div> <!-- col // -->
      	{% endfor %}
	  	{% else %}
  			<p>В магазине пока нет товаров!</p>
		{%endif %}
		</div>
	</div>
  </div>
  </div>
{% endblock %}

I_shop/products/templates/products/navbar.html
{% load cart_tag %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
  <a class="navbar-brand" href="/">Бомжатник</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li {% if request.path == 'contact' %}class="nav-item active"{% else %}class="nav-item"{% endif %}>
        <a class="nav-link" href="/find/Заборы">Заборы<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/find/Мебель">Мебель</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/find/Отделка">Отделка</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="/find/Электроника">Электроника</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mainapp:cart-home' %}">
          <i class="fa fa-shopping-cart"></i> Корзина
          <span class="badge badge-light">{{ request.user| cart_total }}</span>
        </a>
      </li>
       
      <li class="nav-item dropdown">
        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-tie"></i> {{ request.user.username }}
        </a>
        <li class="nav-item">
          <a class="nav-link" href="/accounts/logout/">Выход</a>
        </li>
    
        </div>
      </li>
      {% else %}
       <li class="nav-item">
        <a  class="btn btn-primary" href="/accounts/login/">Вход / Регистрация</a>
      </li>
      {% endif %}
    </ul>
  </div>
  </div>
</nav>

I_shop/products/templates/products/product_detail.html
{% extends 'products/base.html' %}


{% block content %}


<div class="container my-5">

	
<div class="card">
	<div class="row">
		<aside class="col-sm-5 border-right">
<article class="gallery-wrap"> 
<div class="img-big-wrap">
  <div> <a href="#"><img src="{{ product.mainimage.url }}" style="width: 450px"></a></div>
</div> <!-- slider-product.// -->
</article> <!-- gallery-wrap .end// -->
		</aside>
		<aside class="col-sm-7">
<article class="card-body p-5">
	<h3 class="title mb-3">{{ object.name }}</h3>
<p class="price-detail-wrap"> 
	<span class="price h3 text-warning"> 
		<span class="num">{{ object.price }}</span><span class="currency"> руб</span>
	</span> 
	
</p> <!-- price-detail-wrap .// -->
<dl class="item-property">
  <dt>Описание:</dt>
  <dd><p>{{ object.preview_text }}</p>
	<p>{{ object.detail_text }}</p>	
</dd>
</dl>

	<a href="{% url 'mainapp:cart' object.slug %}" class="btn btn-lg btn-outline-primary text-uppercase"> <i class="fas fa-shopping-cart"></i> Добавить в корзину </a>
</article> <!-- card-body.// -->
		</aside> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->


</div>
<!--container.//-->
{% endblock %}